#基本はgithub.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
#[[plugins]]
#repo = 'Shougo/vimproc.vim'
#hook_post_update = '''
#if dein#util#_is_windows()
#let cmd = 'tools\\update-dll-mingw'
#elseif dein#util#_is_cygwin()
#let cmd = 'make -f make_cygwin.mak'
#elseif executable('gmake')
#let cmd = 'gmake'
#else
#let cmd = 'make'
#endif
#let g:dein#plugin.build = cmd
#'''

# ブランチやタグを指定したいとき
[[plugins]]
repo = 'delphinus35/typescript-vim'
rev  = 'colorize-template-strings'

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr/vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
#------------------------------
[[plugins]]
repo = 'Shougo/neocomplcache'
on_i = 1
hook_add = '''
    "基本設定
    let g:acp_enableAtStartup = 0
    let g:neocomplcache_enable_at_startup = 1
    let g:neocomplcache_enable_smart_case = 1
    let g:neocomplcache_min_syntax_length = 3
    let g:neocomplcache_lock_buffer_name_pattern = '\*ku\*'

    " 一番目の候補を自動選択
    let g:neocomplcache_enable_auto_select = 0
    " 補完候補の数
    let g:neocomplcache_max_list = 5
    " 選択して改行されないようにする
    inoremap <expr><CR> pumvisible() ? neocomplcache#close_popup() : "\<CR>"
    "" <TAB>: completion.
    inoremap <expr><TAB> pumvisible() ? "\<C-n>" : "\<TAB>"
    "" <C-h>, <BS>: close popup and delete backword char.

'''

[[plugins]]
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neosnippet'
depends = ['Shougo/neosnippet-snippets']
on_i = 1
#on_ft = ['snippet']

[[plugins]]
repo = 'haya14busa/incsearch.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    "https://kamiya555.github.io/2015/10/14/nerdtree-command/
    " 隠しファイルをデフォルトで表示させる
    let NERDTreeShowHidden = 1

    " ブックマークを初期表示
    let g:NERDTreeShowBookmarks=1

    " デフォルトでツリーを表示させる
    "autocmd VimEnter * execute 'NERDTree'

    " ファイル名指定しなかった場合はデフォルトでNERDTREE表示
    autocmd StdinReadPre * let s:std_in=1
    autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

'''

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_add = '''
    "vimを立ち上げたときに、自動的にvim-indent-guidesをオンにする
    let g:indent_guides_enable_on_vim_startup = 1
    "自動カラー無効
    let g:indent_guides_auto_colors = 0
    "偶数行と奇数行の色を設定
    autocmd VimEnter,Colorscheme * :hi IndentGuidesOdd  guibg=#444433 ctermbg=black "3
    autocmd VimEnter,Colorscheme * :hi IndentGuidesEven guibg=#333344 ctermbg=darkgray "4
    "何行目から色付けを行うかを指定する
    let g:indent_guides_start_level = 2
    "可視化領域のサイズを指定
    let g:indent_guides_guide_size = 1
'''
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'vim-scripts/autodate.vim'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'tyru/eskk.vim'

